---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 655bd73464cbdaafa96903dfa49657cc
    - f8027a903a35137ed66f88336ed77861
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- config/
- tests/
- vendor/
